#!/usr/bin/env php
<?php

    require_once "vendor/autoload.php";
    
$options = getopt("b:");
//var_dump($options);

$birthDate =$options['b'] ?? "1977-08-10";
//$todayDate = date('Y-m-d');
$days = new Splx\Dates\BirthDays($birthDate);
/*
$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime -$birthTime;
$totalDays = floor($totalSecs / 3600 /24);*/
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays" . PHP_EOL;
