#!/usr/bin/env php
<?php

$birthDate = "1977-08-10";
$todayDate = date('Y-m-d');

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime -$birthTime;
$totalDays = floor($totalSecs / 3600 /24);

echo "$birthDate : $totalDays" . PHP_EOL;
